---
title: "Progress Report"
author: "Heike Hofmann"
date: "2022-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Lahman)
library(dplyr)
library(ggplot2)
head(HallOfFame, 3)

HallOfFame %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2024))
```

```{r}
write.csv(HallOfFame, "HallOfFame.csv", row.names = FALSE)
```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)

head(tables[[1]], 3)
```

```{r}
data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)
```

```{r}
data$Votes <- as.numeric(data$Votes)
readr::parse_number(c("34%", "10th", "1.0"))

x <- c("David Ortiz", "X-Barry Bonds", "X-Roger Clemens")
gsub("X-", "Oh no! ", x)

gsub("X-", "", x)

x1 <- data.frame(id=1:2, name=c("A", "B"))
x2 <- data.frame(id=3:4, name=c("C", "D"))
rbind(x1, x2)
dframe <- rbind(x1, x2)

write.csv(dframe, file="iliring's-work.csv", row.names = FALSE)
```
